const actionTypes = {
  SIGNUP: 'SIGNUP',
  LOGINSUCESS: 'LOGINSUCCESS',
  LOGINFAIL: 'LOGINFAIL',
  SIGNUPFAIL: 'SIGNUPFAIL',
  SIGNUPSUCCESS: 'SIGNUPSUCCESS',
  POSTQUESTIONSUCCESS: 'POSTQUESTIONSUCCESS',
  POSTQUESTIONFAILURE: 'POSTQUESTIONFAILURE'
};

export default actionTypes;
